version: '3'

services:
  app1:
    build: .
    volumes:
      - storage:/app/storage
    
  app2:
    build: .
    volumes:
      - storage:/app/storage
  
  app3:
    build: .
    volumes:
      - storage:/app/storage

  app4:
    build: .
    volumes:
      - storage:/app/storage

volumes:
  storage: