version: '3'

services:
  app1:
    image: dfs
    volumes:
      - storage:/app/storage
    
  app2:
    image: dfs
    volumes:
      - storage:/app/storage
  
  app3:
    image: dfs
    volumes:
      - storage:/app/storage

  app4:
    image: dfs
    volumes:
      - storage:/app/storage
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  storage: